### ISSUE TITLE
It will appear when interpreting large files Segmentation fault

### ISSUE THREAD

**Issue by LeeSSXX** [sztupy/luadec51#11]
Core was generated by `./luadec /root/login.lua'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  __strlen_avx2 () at ../sysdeps/x86_64/multiarch/strlen-avx2.S:62
62	../sysdeps/x86_64/multiarch/strlen-avx2.S: No such file or directory.
(gdb) where
#0  __strlen_avx2 () at ../sysdeps/x86_64/multiarch/strlen-avx2.S:62
#1  0x00007f3546003e3e in __GI___strdup (s=0x0) at strdup.c:41
#2  0x000055d603efc78a in ProcessCode (f=0x55d6043e0c40, indent=0) at ../luadec/../luadec/ldprint.c:1969
#3  0x000055d603efd920 in ProcessCode (f=0x55d6043df860, indent=0) at ../luadec/../luadec/ldprint.c:2250
#4  0x000055d603efe031 in luaU_decompile (f=0x55d6043df860, dflag=0) at ../luadec/../luadec/ldprint.c:2342
#5  0x000055d603ef44d5 in main (argc=1, argv=0x7fff33670fd0) at ../luadec/../luadec/luadec.c:410

**Comment by LeeSSXX** [comment]
[api.zip](https://github.com/sztupy/luadec51/files/1957596/api.zip)

**Comment by m1entus** [comment]
+1 @sztupy are you still can handle this one ?
